### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by robinunlearning** [tokboxnerds/opentok-react-native#2]
Hi

I'm getting a build failure. The error is, "/Users/robin/code/opentok-react-native/node_modules/react-native/Libraries/Image/RCTDownloadTaskWrapper.m:65:49: Null passed to a callee that requires a non-null argument

I'm a React Native noob, so any help would be appreciated.

**Comment by thissophie** [comment]
An immediate fix is to edit RCTDownloadTaskWrapper.m (line 65) and change the line so it doesn't have the `callback:nil` argument (might be completionHandler or block, I can't recall). 

The real fix is for me to update this project to the latest version of react-native, will update this issue when I get a chance to do so.

**Comment by robinunlearning** [comment]
Thanks for you help. That change removed the issue, but then there's another build issue then:
opentok-react-native/node_modules/react-native-orientation/RCTOrientation/Orientation.h:16:12: Cannot find interface declaration for 'AppDelegate'

I totally understand this may not be a priority, but just thought I'd mention it.

**Comment by thissophie** [comment]
This should now be fixed (updated to react 0.15.0)
